title: "Hirewire.lk"
description: "HireWire.LK is an on-demand hiring marketplace where employers can connect with jobseekers in real-time."
status: "In Active Development"

author-name: "i am Programmer"
author-url: "https://iamprogrammer.lk"
github-url: "https://github.com/iamprogrammerlk"
x-url: "https://x.com/iamprogrammerlk"
linkedin-url: "https://linkedin.com/company/iamprogrammerlk"
email: "contact@iamprogrammer.lk"
